### ISSUE TITLE
(Possible) Mistake in default parameter comments

### ISSUE THREAD

**Issue by cyb3rko** [lambdapioneer/argon2kt#18]
Moin again.

[This line](https://github.com/lambdapioneer/argon2kt/blob/b0b0ee85656f3a5e3657814de216ce1a102a5da9/lib/src/main/java/com/lambdapioneer/argon2kt/Argon2Kt.kt#L13) got me confused, it says that the default hash length is 32 Bytes which result in 128 Bit output.

Is this a typo (as 32 Bytes are 256 Bit) or is there a misunderstanding on my side?

**Comment by lambdapioneer** [comment]
Hi, you are right, that's a typo and it should say 256 Bit
