### ISSUE TITLE
Migrate from JCenter

### ISSUE THREAD

**Issue by osipxd** [lambdapioneer/argon2kt#5]
Hello! Thank you for this library!

[Bintray is shutting down May 2021 along with JCenter.](https://jfrog.com/blog/into-the-sunset-bintray-jcenter-gocenter-and-chartcenter/)

Existing packages will be served until **February 1st 2022**, new versions can be submitted until **March 31st 2021**.
It would be great to have *argon2kt* in Maven Central.

Here is a bunch of articles that might be helpful:
- https://chris.banes.dev/publishing-to-maven-central/ (Compilation of helpful resources from Chris Banes)
- https://www.marcogomiero.com/posts/2021/move-libray-jcenter-to-maven/ (Migration of old artifacts)
- https://central.sonatype.org/pages/ossrh-guide.html (Official guide. Quite outdated approach to work with Gradle, but other points might be useful)

**Comment by lambdapioneer** [comment]
Hi @osipxd,

Thanks for creating the issue! This is on my list and it will happen in April.

I appreciate the links and Chris's page looks like a good starting point for me.

Cheers,
Daniel

**Comment by lambdapioneer** [comment]
Hi @osipxd ,

This should be fixed now :). If you update your dependency to `com.lambdapioneer.argon2kt:argon2kt:1.3.0`, Gradle should find it on Maven Central.

Let me know whether it works as expected for you (then I'll close this issue).

Cheers,
Daniel

**Comment by osipxd** [comment]
Great news! Thank you, everything works.
