### ISSUE TITLE
salt question?

### ISSUE THREAD

**Issue by ThomasGustafson** [lambdapioneer/argon2kt#7]
First I do want to echo the sentiments of many others in thanking you for creating this library.

I have run into one question / issue.

How do I randomize the salt ?

Thank you for your time

Thomas Gustafson

**Comment by lambdapioneer** [comment]
Hi Thomas!

I'd suggest that you use `SecureRandom` CSRNG from the standard library for this: https://developer.android.com/reference/java/security/SecureRandom

Cheers,
Daniel
